-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 12:19:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisVentasCRPOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisVentasCRPOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisVentasCRPOS` DEFAULT CHARACTER SET utf8 ;
USE `sisVentasCRPOS` ;

-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` TEXT NULL,
  `imagen` VARCHAR(50) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articulo_cateogoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_articulo_cateogoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `sisVentasCRPOS`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(15) NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total_venta` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_persona_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_venta_persona`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `sisVentasCRPOS`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NOT NULL,
  `articulo_id` INT NOT NULL,
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalleVenta_articulo_idx` (`articulo_id` ASC),
  INDEX `fk_detalleVenta_venta_idx` (`venta_id` ASC),
  CONSTRAINT `fk_detalleVenta_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `sisVentasCRPOS`.`articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVenta_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `sisVentasCRPOS`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingreso_persona_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `sisVentasCRPOS`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisVentasCRPOS`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisVentasCRPOS`.`detalle_ingreso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio_compra` DECIMAL(11,2) NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `ingreso_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalleIngreso_ingreso_idx` (`ingreso_id` ASC),
  INDEX `fk_detalleIngreso_articulo_idx` (`articulo_id` ASC),
  CONSTRAINT `fk_detalleIngreso_ingreso`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `sisVentasCRPOS`.`ingreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleIngreso_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `sisVentasCRPOS`.`articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
